# Generated by Django 2.1.5 on 2021-11-03 03:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produk', '0018_auto_20211101_1516'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='material',
            name='durasiProduksi',
        ),
    ]
