# Generated by Django 2.1.5 on 2021-11-01 08:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_dies', models.CharField(max_length=255, unique=True)),
                ('durasi_setup', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Istirahat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('waktu_awal', models.TimeField(blank=True, null=True)),
                ('waktu_akhir', models.TimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='OperatorSK',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=16, unique=True)),
                ('nama', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Perawatan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_usable', models.BooleanField(choices=[(1, 'Iya'), (0, 'Tidak')])),
                ('keterangan_perawatan', models.TextField()),
                ('tanggal_perawatan', models.DateField()),
                ('waktu_awal', models.TimeField()),
                ('waktu_akhir', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Proses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_proses', models.CharField(max_length=255, unique=True)),
                ('nama_proses', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='StasiunKerja',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_stasiun_kerja', models.CharField(max_length=255, unique=True)),
                ('mulai_kerja', models.TimeField()),
                ('selesai_kerja', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Mesin',
            fields=[
                ('stasiunkerja_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='BatchProduction.StasiunKerja')),
                ('id_mesin', models.CharField(max_length=5, unique=True)),
                ('nama_mesin', models.CharField(max_length=255)),
            ],
            bases=('BatchProduction.stasiunkerja',),
        ),
        migrations.AddField(
            model_name='operatorsk',
            name='lokasi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BatchProduction.StasiunKerja'),
        ),
        migrations.AddField(
            model_name='dies',
            name='proses',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BatchProduction.Proses', to_field='id_proses'),
        ),
        migrations.AddField(
            model_name='proses',
            name='mesin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BatchProduction.Mesin', to_field='id_mesin'),
        ),
        migrations.AddField(
            model_name='perawatan',
            name='mesin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BatchProduction.Mesin', to_field='id_mesin'),
        ),
        migrations.AddField(
            model_name='istirahat',
            name='mesin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BatchProduction.Mesin', to_field='id_mesin'),
        ),
    ]
