# Generated by Django 2.1.5 on 2021-11-03 02:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BatchProduction', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='istirahat',
            name='mesin',
        ),
        migrations.DeleteModel(
            name='Istirahat',
        ),
    ]
