# Generated by Django 2.1.5 on 2021-11-03 03:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BatchProduction', '0002_auto_20211103_0959'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perawatan',
            name='mesin',
        ),
        migrations.DeleteModel(
            name='Perawatan',
        ),
    ]
