# Generated by Django 2.1.5 on 2021-11-03 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BatchProduction', '0003_auto_20211103_1018'),
    ]

    operations = [
        migrations.AddField(
            model_name='proses',
            name='durasiProduksi',
            field=models.IntegerField(default=15),
            preserve_default=False,
        ),
    ]
