# Generated by Django 2.1.5 on 2021-11-01 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JadwalBatchProduction', '0002_targettahunan'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProduksiHarian',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material', models.CharField(choices=[('V01', 'V01')], max_length=255)),
                ('target', models.IntegerField()),
                ('selesai', models.IntegerField(default=0)),
                ('tanggal', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='TargetBulanan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material', models.CharField(choices=[('V01', 'V01')], max_length=255)),
                ('target', models.IntegerField()),
                ('selesai', models.IntegerField(default=0)),
                ('bulan', models.IntegerField(choices=[(1, 'Januari'), (2, 'Februari'), (3, 'Maret'), (4, 'April'), (5, 'Mei'), (6, 'Juni'), (7, 'Juli'), (8, 'Agustus'), (9, 'September'), (10, 'Oktober'), (11, 'November'), (12, 'Desember')])),
                ('tahun', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TargetHarian',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.DateField(unique=True)),
                ('waktumulai', models.TimeField(null=True)),
                ('waktuselesai', models.TextField(null=True)),
                ('is_digabung', models.CharField(choices=[('Gabung', 'Gabung'), ('Tidak', 'Tidak')], max_length=6)),
                ('is_libur', models.BooleanField(default=False)),
                ('is_dijadwal', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='TargetMingguan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material', models.CharField(choices=[('V01', 'V01')], max_length=255)),
                ('target', models.IntegerField()),
                ('selesai', models.IntegerField(default=0)),
                ('minggu', models.IntegerField()),
                ('tahun', models.IntegerField()),
            ],
        ),
    ]
