# Generated by Django 2.1.5 on 2021-11-03 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JadwalBatchProduction', '0003_produksiharian_targetbulanan_targetharian_targetmingguan'),
    ]

    operations = [
        migrations.CreateModel(
            name='Istirahat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.DateField(blank=True, null=True)),
                ('waktu_awal', models.TimeField(blank=True, null=True)),
                ('waktu_akhir', models.TimeField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='targetbulanan',
            name='tahun',
            field=models.IntegerField(choices=[(2021, 2021)]),
        ),
        migrations.AlterField(
            model_name='targetmingguan',
            name='tahun',
            field=models.IntegerField(choices=[(2021, 2021)]),
        ),
    ]
