# Generated by Django 2.1.5 on 2021-11-04 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JadwalBatchProduction', '0005_perawatan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produksiharian',
            name='material',
            field=models.CharField(choices=[('V01', 'V01'), ('V02', 'V02'), ('V03', 'V03'), ('V04', 'V04')], max_length=255),
        ),
        migrations.AlterField(
            model_name='targetbulanan',
            name='material',
            field=models.CharField(choices=[('V01', 'V01'), ('V02', 'V02'), ('V03', 'V03'), ('V04', 'V04')], max_length=255),
        ),
        migrations.AlterField(
            model_name='targetmingguan',
            name='material',
            field=models.CharField(choices=[('V01', 'V01'), ('V02', 'V02'), ('V03', 'V03'), ('V04', 'V04')], max_length=255),
        ),
        migrations.AlterField(
            model_name='targettahunan',
            name='material',
            field=models.CharField(choices=[('V01', 'V01'), ('V02', 'V02'), ('V03', 'V03'), ('V04', 'V04')], max_length=255),
        ),
    ]
